redpanda-console:
  replicaCount: 1

  image:
    repository: redpandadata/console
    tag: v3.3.2
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 8080

  # Kafka configuration
  kafka:
    brokers:
      - dbrep-kafka:9092

  # Kafka Connect configuration
  connect:
    enabled: true
    clusters:
      - name: kafka-connect-v2
        url: http://dbrep-kafka-connect-cp-kafka-connect:8083
      - name: kafka-connect-v3
        url: http://dbrep-kafka-connect-v3-cp-kafka-connect:8083

  resources:
    limits: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
